federated:
  image: dilawarm/federated:latest
  script:
    - make test
    - black .
  artifacts:
    paths:
      - coverage/

deploy_docs:
  image: node:latest
  script:
    - apt update
    - apt install -y python3-pip
    - pip3 install pip==21.0.1
    - pip3 install -r requirements.txt
    - cd docs && make html
    - npm install -g firebase-tools
    - firebase use --token $FIREBASE_DEPLOY_KEY federated-docs
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY