federated:
  image: dilawarm/federated:latest
  script:
    - make test
    - black .

deploy_docs:
  image: node:latest
  script:
    - apt update
    - apt install -y python3-pip
    - pip3 install -r requirements.txt
    - cd docs && make html