image: ubuntu:latest

before_script:
  - apt-get clean
  - apt-get update
  - apt install -y python3-dev python3-pip
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt

test:
  script:
    - make test

format:
  script:
    - black .