name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install --upgrade pip
          pip3 install -r requirements.txt
          cd docs && make html
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FEDERATED_DOCS }}'
          channelId: live
          projectId: federated-docs
