name: Test and Format federated
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup
      - run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install --upgrade pip
          pip3 install -r requirements.txt
      - run: python3 -m pytest --cov=federated/ federated/tests/
      - run: black .
