name: Test and Format federated
'on':
  push:
    branches:
      - master
jobs:
  test_and_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install --upgrade pip
          pip3 install -r requirements.txt
      - name: tests
        run: |
          python3 -m pytest --cov=federated/models/ federated/tests/models_test.py
          python3 -m pytest --cov=federated/utils/training_loops.py federated/tests/training_loops_test.py
          python3 -m pytest --cov=federated/utils/rfa.py federated/tests/rfa_test.py
      - run: black .
